# Generated by Django 4.1.3 on 2022-11-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pruebaping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebaping',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.equipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pruebaping',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
